#actable的配置信息
actable:
  table:
    auto: update
  model:
    pack: com.mashibing.elk.esclient.base.entity
  database:
    type: mysql
mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

#druid数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.151.4:3306/msb_elk?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root@123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
